branches:
  only:
    - gh-pages
git:
  depth: 1
language: python
python:
    - 2.7
before_install:
  - rvm use 2.2.3 --install --fuzzy
install:
  - travis_retry gem install --no-document jekyll
  - pip install -r requirements.txt
script:
  - rm index.md
  - make
